name: codeverse-dmx-controller
version: 0.0.1
architectures:
  - build-on: armhf
summary: DXM Controller for Codeverse module
description: |
  A simple dmx controller which exposes a web API, runs on a Codeverse module and used within the Codeverse Studios
confinement: strict
grade: stable
build-packages: [gcc]

apps:
  web-api:
    command: webserver www
    daemon: simple
    restart-condition: always
    plugs:
      - network-bind

  dmx-server:
    command: dmx-server
    daemon: simple
    restart-condition: always
    environment:
      LD_LIBRARY_PATH: /snap/codeverse-dmx-controller/current/usr/local/lib
    plugs:
      - gpio-memory-control
      - network-bind

  dmx-client:
    command: dmx-client

parts:
  web-api:
    source: .
    plugin: go
    go-importpath: github.com/americademy/dmx-controller-snap

  dmx-server:
    source: .
    source-subdir: dmx-server
    plugin: make

  dmx-client:
    source: .
    source-subdir: dmx-client
    plugin: make
